name: Terraform Plan

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  preview:
    name: Plan Terraform changes in changed stacks
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      checks: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          enable-cache: true

      - name: Configure Devbox Shell Environment
        run: |
          eval "$(devbox shellenv)"
          printenv >> $GITHUB_ENV

      - name: List changed stacks
        id: list-changed
        run: terramate list --changed

      - name: Configure AWS credentials
        if: steps.list-changed.outputs.stdout
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Run Terraform Init
        if: steps.list-changed-stacks.outputs.stdout
        run: |
          terramate run --changed -- terraform init -detailed-exitcode

      - name: Run Terraform Plan
        if: steps.list-changed-stacks.outputs.stdout
        run: |
          terramate run \
            --changed \
            --continue-on-error \
            --parallel 3 \
            -- \
            terraform plan -input=false -detailed-exitcode
